- name: Deploy ecommerce application
  yum:
    name:
      - libselinux-python
      - libsemanage-python
      - firewalld
    state: installed

    
- name: Install MariaDB package
  yum:
    name:
    - mariadb-server
    - MySQL-python
    state: installed

- name: Create Mysql configuration file
  copy: src=files/my.cnf dest=/etc/my.cnf

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started enabled=yes

- name: insert firewalld rule
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host='localhost' state=present

- name: Move db-load-script to db host
  copy:
    src: files/db-load-script.sql
    dest: /tmp/db-load-script.sql

- name: Load Inventory Data
  shell: mysql -f < /tmp/db-load-script.sql
          
